### ISSUE TITLE
Research Logging

### ISSUE THREAD

**Issue by lautarodragan** [poetapp/node#1]
Bunyan + Loggly seems like a good place to start.

https://github.com/trentm/node-bunyan
https://www.loggly.com/plans-and-pricing/
https://www.loggly.com/docs/node-js-logs/
https://www.npmjs.com/package/bunyan-loggly

Make a small, stand-alone nodejs project that uses Bunyan + Loggly to test it.

**Comment by patrickleet** [comment]
```
npm i --save llog pino
```
^ json leveled logging

```
import log from 'llog'

log.info({msg: 'hello', id: 123})
log.debug('only show when log level is debug')
log.error('error')
```

Then, using docker swarm, on each node, run cAdvisor to pick up all container logs, and open source ELK stack!

**Comment by patrickleet** [comment]
all services should just log to stdout - shipping logs shouldnt be responsibility of service

**Comment by lautarodragan** [comment]
Thanks for the suggestion @patrickleet ! We'll stay way from peer dependencies but Pino does seem like a good option. The benchmarks are really nice, and looks like Bunyan in everything else.

Also, I agree all services should just log to stdout and another application should take care of shipping, aggregation, etc. We'll stay away from tying Po.et to loggly.
