### ISSUE TITLE
Coveralls

### ISSUE THREAD

**Issue by lautarodragan** [poetapp/node#11]
Integrate with Coveralls.

Automatically reject PRs that lower the % of test coverage.

**Comment by patrickleet** [comment]
this can also be set on precommit or prepush pretty easily - see my article here:

https://hackernoon.com/i-have-a-confession-to-make-i-commit-to-master-6a804f334beb

you may still want the reporting, but, could just set to 100% and call it a day. 

Article uses jest as a reference - not sure what you are using, but sure it's a similar setup.

**Comment by warrenv** [comment]
Closing - We're going to use nyc to do this.
