### ISSUE TITLE
poet-js package

### ISSUE THREAD

**Issue by kennylavender** [poetapp/node#115]
Which npm package of `poet-js` is correct?
https://www.npmjs.com/search?q=poet-js

This repo is currently using `poet-js`, but I think it needs to be changed to `@poet/poet-js`?
https://github.com/poetapp/node/blob/master/package.json#L44

**Comment by wzalazar** [comment]
@kennylavender you are right!!!  good catch 

it's wrong this dependency

it is our organization in NPM

https://www.npmjs.com/settings/po.et/packages

and the package would be:

https://www.npmjs.com/package/@po.et/poet-js

**Comment by kennylavender** [comment]
Cool thanks! I will make an issue for myself to fix it
