### ISSUE TITLE
IPFS Download Failure Detail

### ISSUE THREAD

**Issue by lautarodragan** [poetapp/node#121]
Related to #53 

Our procedure to download files from IPFS currently takes any failure at all and marks the download request as failed, increasing the attempt count for it, but ignoring the details of what exactly went wrong.

https://github.com/poetapp/node/blob/3e624760b0e7d546898b966cb393161893debd02/src/Storage/ClaimController.ts#L76-L99

https://github.com/poetapp/node/blob/3e624760b0e7d546898b966cb393161893debd02/src/Storage/ClaimController.ts#L180-L190

We need to add support to distinguish between network timeout errors and "not a claim" errors.

**Comment by lautarodragan** [comment]
[QmcncKtWRDgvbDiKqxH9rAzT6DGAFsHqTEnZ2WbQURNdpb](https://ipfs.io/ipfs/QmcncKtWRDgvbDiKqxH9rAzT6DGAFsHqTEnZ2WbQURNdpb) is in [block 1282565](https://test-insight.bitpay.com/block/0000000000000923ab8b3d9bfb84c330a756eb41cca1c8fbfe42bb98a2da6c20), [transaction 6cdddbb771d4edff5481280c165e03764f046726b57737fba6a28e100c4e7bd2](https://test-insight.bitpay.com/tx/6cdddbb771d4edff5481280c165e03764f046726b57737fba6a28e100c4e7bd2).

**Comment by lautarodragan** [comment]
Some initial tests with the WIP failure detail:

```
> db.works.count()
9581
> db.storage.count()
9558
> db.storage.find({claimId: null}).count()
1709
> db.storage.find({claimId: {$ne: null} }).count()
7849
> db.storage.find({failureReason: 'invalid'}).count()
1704
> db.storage.find({failureReason: 'unknown'}).count()
0
> db.storage.find({$and: [ {failureReason: {$ne: 'invalid' }}, {failureReason: {$exists: true} } ]} ).count()
0
```

**Comment by kennylavender** [comment]
The failures might just be due to the download timeout, 10 seconds may still not be enough. I've manually tested a few of my local download failures by putting the URL in my browser, sometimes it takes the ipfs network upwards of 30+ seconds to find a node to download the claim.

**Comment by geoffturk** [comment]
Yup, same here. Some files have been easily above 10 seconds but probably always under 30 in my experience.
