### ISSUE TITLE
IPFS - Republisher failed to republish

### ISSUE THREAD

**Issue by WesleyCharlesBlake** [poetapp/node#125]
I see the following error in IPFS:

```07:20:32.785 ERROR ipns-repub: Republisher failed to republish: failed to find any peer in table repub.go:78```

As per [this issue](https://github.com/ipfs/go-ipfs/issues/1941), it would appear that it happens when intentionally running a single peer.e

Is this a breaking bug? something we can live with in dev? or something that we need to address

**Comment by geoffturk** [comment]
@lautarodragan @kennylavender Is this an issue still? Please sync with Wes if you need more recent log input.

**Comment by kennylavender** [comment]
@WesleyCharlesBlake is this still happening? and in what environments?

Seems like this is only an issue in the cases where we need IPFS to be connected to peers, production/testing/staging etc.

From issue comments it sounds like this error should only show up if we are preventing IPFS from connecting to outside peers, I can't think of a reason we would be doing that on purpose, are we?

**Comment by geoffturk** [comment]
@kennylavender No, we are not.

@WesleyCharlesBlake Is this still showing up in the logs?
