### ISSUE TITLE
Inversify: Use Symbols instead of strings

### ISSUE THREAD

**Issue by lautarodragan** [poetapp/node#14]
We're using hard-coded strings to identify bound classes and constants in Inversify.

Inversify [supports and recommends](https://github.com/inversify/InversifyJS/blob/master/wiki/symbols_as_id.md) using Symbols instead of strings for this.

**Comment by kennylavender** [comment]
@lautarodragan If we are going to refactor to factories, do we still want to use a DI Frameworks and symbols? I am thinking we should ditch DI Frameworks all together and do manuall dependency injection.

From what I can tell there is very little benfit of this inversify DI Framework, but many drawbacks.

Inversify Benifits
- No worrying about argument order, but this is a tiny benfit, a single argument object can be used to get this same benifit.
- Don't need to pass the same instance to multiple objects, again this is a very tiny benifit as the instance will already be in an argument and its just simply passing it through to classes/factories that need it.

Inversify Drawbacks

- Another unecessary complex dependency
  - another point of failure in the future: bugs/issues/security
- Layer of indirection that isn't trully helpfull
- Doesn't seem to reduce code
  - seems to actually increase the amount of code
  - even with Symbols, Symbols require even more code. export/import symbols everywhere along with the interfaces and classes.
  - Symbols seem to a solution to problems that DI Frameworks create by trying to name dependencies with strings.
- DI framework litterred throughout the codebase in every module


I was thinking about creating a side by side comparison between to test my assumptions above.

- classes + inversify and symbols
- factories + inversify and symbols
- factories manuall dependency injection

Let me know your thoughts and if I missed anything, and  let me know if you would like to see this RDD comparison.

**Comment by wzalazar** [comment]
@kennylavender sound great idea the possibility to compare different approaches. For my side, I think the manual injection is more easy to understand

**Comment by lautarodragan** [comment]
I mostly agree with everything. 

I would still like to use DI with factories, but from my tests it seems not to be possible at all, and I  [haven't gotten a reply about this in 3 weeks](https://github.com/inversify/InversifyJS/issues/993).

The only alternative I can think of is manually calling the factories from the composition root, which is similar to what we are already doing but more verbose and cumbersome. I think this is what you mean too, by _factories manuall dependency injection_

> Let me know your thoughts and if I missed anything, 

Spot on IMO.

Maybe I'd add that DI containers are a form of global state, which is another point against InversifyJS.

> and let me know if you would like to see this 123456
RDD comparison.

I'd go with just creating an example of `factories manual dependency injection`, but no need for any fancy comparison or RDD IMO.

Parking this issue for now, as it may not be relevant anymore.

**Comment by kennylavender** [comment]
>  I think this is what you mean too, by factories manuall dependency injection
Yup.

> Maybe I'd add that DI containers are a form of global state, which is another point against InversifyJS.

👍 added to the list

> I'd go with just creating an example of factories manual dependency injection, but no need for any fancy comparison or RDD IMO.

Cool, Il probably just refactor one of the modules completely to give us an idea, then we can go from there.

**Comment by lautarodragan** [comment]
> Cool, Il probably just refactor one of the modules completely to give us an idea, then we can go from there.

Awesome :rocket: Created https://github.com/poetapp/node/issues/830 so we can track that work.

**Comment by lautarodragan** [comment]
No longer needed after https://github.com/poetapp/node/pull/836
