### ISSUE TITLE
Add env var to control claim batch transaction frequency

### ISSUE THREAD

**Issue by geoffturk** [poetapp/node#151]
Given how widely bitcoin transaction fees can fluctuate, we want to give node operators control over how often a claim batch is written to the blockchain. When (not if) the fees go sky high again, node operators might want to limit claim batches to once every hour or even just 4-6 times per day.

We should add an env var that would allow us to control the frequency of claim batches being written to the blockchain.

needed-by poetapp/node#20

**Comment by geoffturk** [comment]
@lautarodragan In [src/Configuration.ts](https://github.com/poetapp/node/blob/master/src/Configuration.ts#L50) there is an env var called `timestampIntervalInSeconds `. What purpose does it serve right now?

Can it be re-used to control the frequency of writing transactions to the blockchain when we start batching claims?

**Comment by lautarodragan** [comment]
Totally! That’s what it’s doing right now so it makes sense for it to control the frequency of claim batch transaction frequency

**Comment by geoffturk** [comment]
Excellent! Thanks for confirming.
