### ISSUE TITLE
Secure HTML entities

### ISSUE THREAD

**Issue by wzalazar** [poetapp/node#153]
With the goal to protect us over XXS attacks, we have to sanitize the data in all `JSON.stringify`

I found this library: https://github.com/yahoo/serialize-javascript

**Comment by warrenv** [comment]
Looks like a good solution. :+1:

**Comment by wzalazar** [comment]
@geoffturk the team decided to leave without effect the approach to sanitize the input to Frost-api. You can check the discussion on this ticket https://github.com/poetapp/frost-api/pull/125
