### ISSUE TITLE
PinoJS

### ISSUE THREAD

**Issue by lautarodragan** [poetapp/node#16]
Drop all console.log / console.error in favor of PinoJS.

All logging must be structured.

Define a basic loggin structure structure. Current candidate is:

```
{
  "module": "Storage",
  "file": "ClaimController",
  "method": "downloadNextHash",
  "message": "A more human-readable message describing what's going on",
  extraVariables,
  alwaysUsingShorthandPropertyNames,
}
```

**Comment by patrickleet** [comment]
I'd recommend checking out pino.

Regardless, just use `llog`, which uses `pino` or `bunyan` as a peer dependency, so it will use whatever one is installed, but with a uniform API.

See https://github.com/poetapp/node/issues/1
