### ISSUE TITLE
Timestamping Structure — Reduce Version Size + Add Storage Protocol Identifier 

### ISSUE THREAD

**Issue by lautarodragan** [poetapp/node#174]
We want to update the way we're writing and reading messages in the Bitcoin blockchain.

https://github.com/poetapp/node/blob/5ab6161fd769b0239f8be81751202c4fb3a816bb/src/BlockchainReader/MAINNET_RDD.md

# Now

We're storing 4 bytes for the version.
We're not storing a storage protocol identifier.

# Changes

We want to limit the version space to 2 bytes.
We want to store 1 byte of storage protocol identifier after the version.

```ts
enum StorageProtocol {
  IPFS = 0,
}
```

# Tasks
- Update BlockchainWriter
- Update BlockchainReader

Needs https://github.com/poetapp/node/issues/92
Needs https://github.com/poetapp/node/issues/93
Needs https://github.com/poetapp/node/issues/418

**Comment by geoffturk** [comment]
@lautarodragan I'm assigning this to you for now. We can reassign later (maybe to Walter) if needed.

I linked the issues 92 & 93 as well in CodeTree.

**Comment by geoffturk** [comment]
@lautarodragan When you complete this one, can you please update this document:
https://github.com/poetapp/random/blob/master/Bitcoin%20Anchoring.md

Maybe take elements from the beginning of [this other document on timestamping](https://github.com/poetapp/random/blob/master/Timestamping.md) so we have something we can use in the documentation repo.

**Comment by ericelliott** [comment]
> can you please update this document

I think this change will bring the code in line with the specification in that document. Do we need more in that document?

**Comment by ericelliott** [comment]
> Maybe take elements from the beginning of this other document on timestamping so we have something we can use in the documentation repo.

That other document is showing its age. Maybe we can merge the two and delete the old stuff. =)

**Comment by lautarodragan** [comment]
Yep! After I'm done with this it's probably a good time to merge and update all that doc

**Comment by lautarodragan** [comment]
@geoffturk @ericelliott https://github.com/poetapp/documentation/issues/1
