### ISSUE TITLE
No more console.log — Configuration.ts

### ISSUE THREAD

**Issue by lautarodragan** [poetapp/node#191]
Configuration.ts has two `console.log` calls in the `loadConfigurationFromFile` function, which provide information about the path of the configuration file.

`loadConfigurationFromFile` can't use Pino since the instantiation of Pino depends on the configuration, which isn't loaded at that time.

These log messages merely inform about the path of the configuration file, which is a hard-coded constant, so I believe we can remove them safely.

If we want to inform the user what mechanisms were used to load the configuration, maybe we can have the two configuration-loading functions return a key in the configuration `loadedFromFile: boolean` and `loadedFromEnv: boolean`, add optional arguments to the application such as `npm run test-configuration` or some other approach.

**Comment by warrenv** [comment]
I vote for removing them.
