### ISSUE TITLE
Travis Node Sync Testing

### ISSUE THREAD

**Issue by lautarodragan** [poetapp/node#22]
We can configure Travis to run 2 nodes inside docker containers. 

### We'll need
- COPY dist/babel, package.json, etc., to ensure we're running the code being pushed and that the containers are isolated from each other.
- Run two bitcoind containers in -regtest, and `addnode` each other.
- Run two IPFS containers.
- Run two MongoDBs. This one is easy: just use two different connection URLs: `mongodb://localhost:27017/poet1` and `mongodb://localhost:27017/poet2`.
- Run two RabbitMQs. We're currently using Travis' `services` for this - we'll have to check whether Travis supports running more than one of the same service or use a docker container otherwise. 

Then we'll have to build some special integration tests to test replication across nodes. We could have some environment variables that are picked up by integration tests, such as `SECONDARY_NODE_URL`.

**Comment by patrickleet** [comment]
you may want to consider docker-compose and jenkins instead of travis

**Comment by warrenv** [comment]
Completed with https://github.com/poetapp/node/pull/545
