### ISSUE TITLE
Build out unit tests

### ISSUE THREAD

**Issue by geoffturk** [poetapp/node#228]
This should be ongoing as we write new code and update already written code.

This ticket will be closed once we reach 80% code coverage on unit tests in this repo.

**Comment by warrenv** [comment]
This should be ongoing as we write new code and update already written code.
This ticket would be closed once we reach 80% code coverage on unit tests across
all app repos:
  - frost-web
  - explorer-web
  - node
  - frost-api
  - poet-js
  - frost-client

**Comment by geoffturk** [comment]
Good point. I've added this message to the other unit test tickets in the other repos:

>This should be ongoing as we write new code and update already written code.
>
>This ticket will be closed once we reach 80% code coverage on unit tests on this repo.
