### ISSUE TITLE
Build out integration tests

### ISSUE THREAD

**Issue by geoffturk** [poetapp/node#229]

**Comment by geoffturk** [comment]
@warrenv How shall we define 'done' for this ticket (not sure % coverage is applicable here)?

**Comment by warrenv** [comment]
I'm guessing 80% just like unit tests, but it is a good question. We
probably need to get the coverage reports in place first and see where we
are and the effort that's going to be involved to get to some number X.

**Comment by warrenv** [comment]
The following changes need to be made to share a database server for integration (and functional) testing:
  - Construct mongodbUrl from new env vars MONGO_HOST, MONGO_PORT, MONGO_USER, MONGO_PASSWORD, MONGO_DATABASE
 - update test/PrepareDB.ts to get mongo url from the src/Configuration.ts like app does.
 - Modify integration tests to start the node server internally so they can easily override database (and eventually other services like rabbitmq). See pwned-checker for how this is done. https://github.com/poetapp/pwned-checker/blob/master/tests/integration/index.js

As a bonus for changing the integration test startup, we'll have working integration coverage reports.
