### ISSUE TITLE
Separate file storage from work claim storage

### ISSUE THREAD

**Issue by geoffturk** [poetapp/node#260]
We need the ability for users to hash and create claims without storing the files on our IPFS nodes. Both node and frost-api should be able to accommodate this use case. In other words, users should be able to specify arbitrary archive URLs and skip the upload phase.

UPDATE:
Frost API will need to remain backwards compatible with the old claim structure. Node's API can have breaking changes.

See: https://github.com/poetapp/documentation/blob/master/rdd/separate-file-uploads.md

**Comment by kennylavender** [comment]
@ericelliott @lautarodragan 

Checking on a couple things here, my assumptions and endpoint changes

My assumption is that we are separating the uploading of works completely from claims. By that I mean we will no longer support claims being posted with work data directly in the claim as we currently do. Let me know if I am wrong about that assumption is wrong and we will still support claims that contain work content.

If my assumption is correct, then we will want 2 separate endpoints.

Currently, claims are posted via the `/works` endpoint. Shall we rename the claims endpoints to be `/claims/` and then use `/works` for uploading works? or do you guys have other ideas for the endpoint structure?

**Comment by ericelliott** [comment]
We should be able to allow separate file uploads without breaking changes to the existing API.

Unless it's absolutely necessary, we should never introduce breaking changes to the Frost API.

**Comment by kennylavender** [comment]
Ok, thanks, @ericelliott 

Sounds like I can start by creating an endpoint for uploading works that won't cause breaking changes.
@lautarodragan I am not too sure of what plans we have for the current endpoints. Do you have any suggestions for this endpoint? maybe a post to `/works/content` or just `/content` or maybe there is a better word for this. I think it would actually be good for you and me to meet to discuss some of these things.


After the endpoint is created we need to support a claim being posted in both formats, the original format where the claim attributes contain a `content` string and then the separated format where the attributes contain `hash and `archiveUrl` and no `content`. Looking at poet-js, I don't see anything preventing us from adding the extra claim attributes we will need to accept a separated work. We will need to make `content` optional on the Work type https://github.com/poetapp/poet-js/blob/master/src/Interfaces.ts#L40

**Comment by kennylavender** [comment]
to clarify, everything I said above in both my comments is about the node, not the frost-api.

**Comment by geoffturk** [comment]
Related to: https://github.com/poetapp/random/issues/98

**Comment by lautarodragan** [comment]
> My assumption is that we are separating the uploading of works completely from claims. By that I mean we will no longer support claims being posted with work data directly in the claim as we currently do. Let me know if I am wrong about that assumption is wrong.

I think that's right.

**Comment by geoffturk** [comment]
How will this affect existing stuff like the WP plugin? Will this be a breaking change?

**Comment by kennylavender** [comment]
I believe the node is complete in regards to this issue with the closing of #612

frost-api still needs to be adjusted to use the new files endpoint to maintain backwards compat with the old `content` property of claims.
