### ISSUE TITLE
Testing Environment

### ISSUE THREAD

**Issue by lautarodragan** [poetapp/node#28]
Build with terraform. 

The Testing Environment needs to have two completely isolated Po.et Nodes, each with its own IPFS, MongoDB and RabbitMQ. 

Initially, they'll be timestamping to testnet.

Once #24 is complete, we'll be able to add a bitcoind -regtest that generates new blocks every minute to the formula, and have a separate, staging environment that uses the public testnet.

**Comment by geoffturk** [comment]
Achieved in our Mainnet release. 🎉
