### ISSUE TITLE
Unit tests excluded from TSLint

### ISSUE THREAD

**Issue by lautarodragan** [poetapp/node#280]
TSLint ignores files excluded in tsconfig.json.

We currently have the following configuration:

```json
  "exclude": [
    "./src/**/*.test.ts"
  ]
```

I can't find any way to indicate TSLint that we DO want these files to be linted. I think the best approach right now would be to simply not exclude them.

We currently have about 14 lint errors in `*.test.ts` files

**Comment by warrenv** [comment]
This was added to omit unit test files from the dist/ directory during a build.
I'm looking at a way to have eslint include them.

**Comment by warrenv** [comment]
@lautarodragan What command did you run to see linting errors in the test files?
If I omit the exclude statement from `tsconfig.json`, I get a clean lint run.

**Comment by lautarodragan** [comment]
@warrenv I uncommented the exclusion and then fixed them in a PR. I don't remember whether I fixed them all or someone else finished that job.

You should be able to reproduce it, though, by introducing a known lint error and expecting the linter to fail.
