### ISSUE TITLE
Health Endpoint

### ISSUE THREAD

**Issue by lautarodragan** [poetapp/node#376]
Should return info about
- connectivity to IPFS, RMQ, DB, Bitcoin Core
- state of retries
- state of ipfs hashes that were given up
- failed transaction broadcasts
- bitcoin core getblockchaininfo 
- - blocks
- - verificationprogress
- - bestblockhash
- - warnings
- - size_on_disk
- bitcoin core getnetworkinfo 
- - version
- - subversion
- - connections
- - networkactive
- - protocolversion
- - warnings
- bitcoin core getwalletinfo 
- - balance
- - txcount
- TBD

### Light Mode

Should support a `light` mode that does no heavy operations so it can be queried on a short interval and a `heavy` mode that offers greater insight.

### Implementation

Probably we'll want to add a new Health module responsible for collecting and aggregating this information.

The new endpoint will need to be added to the API module, so we'll have to figure out the best way for the API module to read this information. Most likely just let the API module directly read from the Health Module's DB, same way we're doing with the View module.

**Comment by WesleyCharlesBlake** [comment]
We need to be careful to not disclose private endpoints / URIs
