### ISSUE TITLE
Readme: Arch

### ISSUE THREAD

**Issue by lautarodragan** [poetapp/node#38]
Add info about the Node's architecture to the readme. 
- What modules there are 
- How they communicate
- [The graph](https://blog.po.et/po-et-node-2-0-60bde69e2e62)

**Comment by lautarodragan** [comment]
Yes, information about coding style, which layers there are, what files do what, what patterns to follow when adding new stuff...

**Comment by geoffturk** [comment]
@lautarodragan I am going to reassign this one to you since you have a clearer idea about what you want to cover. Please loop me in as the main reviewer for PRs on this though. Thanks.

**Comment by lautarodragan** [comment]
Closing this as duplicate of https://github.com/poetapp/node/issues/38
