### ISSUE TITLE
Drop make docker commands in favor of docker-compose

### ISSUE THREAD

**Issue by lautarodragan** [poetapp/node#403]
We already have a docker-compose.yml file.

It's probably easier for everyone to just `docker-compose up -d` which is more standard than having to learn custom make commands.

One blocking requirement is for the node's docker image to be opt-in, since it slows down development and complicates things like step-by-step debugging.

Once possible way to achieve that would be `docker-compose -f docker-compose.yml -f docker-node.yml`, or just `docker-compose -f docker-node.yml` and have `docker-node.yml` expend `docker-compose.yml`.

Will want to update README about this, too.

**Comment by geoffturk** [comment]
Assigning to Warren to tackle when he is back next week.

Please add me as a reviewer to your PR and I will add/review any changes to the README.

**Comment by lautarodragan** [comment]
Update by @warrenv's suggestion: probably more reasonable to separate the dependencies, so new comers can just `docker-compose up -d` and get everything running without having to think of what files to `-f`.

That way I can still `-f docker-compose.overrides.yml`, I believe. TBC.

See https://github.com/poetapp/node/issues/468 for a list of make commands we should be able to drop.
