### ISSUE TITLE
Refactor docker-compose: split poet-node

### ISSUE THREAD

**Issue by lautarodragan** [poetapp/node#430]
## Problem

`docker-compose up` will start all services, including the node itself.

Running the node inside a container slows down the development process a bit and isn't desired by everyone, since it's ever changing.

Running the dependencies in containers, on the other hand, is almost always desirable, since they hardly ever change.

To achieve this, the only solution at the moment is to manually select each service to run: 

```
docker-compose up -d poet-{rabbit,mongo,ipfs} bitcoin-regtest
```

## Proposal

Split the `poet-node` service to a separate `docker-compose.node.yml`.

```
# To run all services
docker-compose -f docker-compose.yml -f docker-compose.node.yml up -d

# To run dependencies only
docker-compose up -d
```

## Questions

Is the docker-compose.yml file being used by other services? Would this change require changes in other code bases?

@warrenv @WesleyCharlesBlake

**Comment by warrenv** [comment]
I would switch the proposed order around so that anyone bring the repo up for the first time or just wanting to check it out can just 'docker-compose up'. 

I haven't used the multiple -f approach much - what if I want to do development using the container? Does a docker-compose.override.yml file still work so I can mount the repo in the container?

**Comment by lautarodragan** [comment]
> I would switch the proposed order around so that anyone bring the repo up for the first time or just wanting to check it out can just 'docker-compose up'.

That would work. It does make sense for first-comers to just `docker-compose up`, not having to think about what `-f` to pass to it.

> I haven't used the multiple -f approach much - what if I want to do development using the container? Does a docker-compose.override.yml file still work so I can mount the repo in the container?

I believe in that case you also need to pass the override manually: `-f docker-compose.override.yml`.
