### ISSUE TITLE
Refactor docker-compose.yml

### ISSUE THREAD

**Issue by lautarodragan** [poetapp/node#431]
Most services in it are currently prefixed with `poet-`.

I believe this was carried over from when we were using the makefile to handle the docker images.

Docker compose itself adds context and prefixes the created images and containers, so it's no longer necessary to do so manually.

**Comment by warrenv** [comment]
I don't believe the build namespaces images, only container names. poet-node would definitely conflict with node (nodejs).

**Comment by warrenv** [comment]
Run 'docker images' after a `docker-compose build` - I'm not prefixes on the poet related images.
