### ISSUE TITLE
Add Wallet Balance Alert to Health Endpoint

### ISSUE THREAD

**Issue by lautarodragan** [poetapp/node#435]
- [ ] Add wallet balance alert threshold to the detailed health endpoint (@jwicks) when the balance drops below a pre-defined (env var) bitcoin amount.

**Comment by lautarodragan** [comment]
Forgot to add a description to this one at the moment I created it...

I believe this one came out of the bitcoin-core meeting, and it was about the node throwing errors when there are insufficient funds in the wallet, rather than correctly detecting this and logging it.

**Comment by geoffturk** [comment]
Yup, that was the context.

**Comment by jwicks31** [comment]
Moved the last part of this issue to [a new](https://github.com/poetapp/node/issues/629) issue
