### ISSUE TITLE
Use rpcauth instead of rpcpassword

### ISSUE THREAD

**Issue by lautarodragan** [poetapp/node#439]
Bitcoin supports two different authentication mechanisms: passing the `rpcuser` and `rpcpassword` pair, which is deprecated and unsafe, and a newer and safer one, `rpcauth`.

`rpcauth` is the username and **hashed** password for JSON-RPC connections. The field <userpw> comes in the format: `<USERNAME>:<SALT>$<HASH>`.

## Implementation

The actual change to the code should be minimal (just replacing `bitcoinUsername` and `bitcoinPassword ` for `bitcoinAuth`).

https://github.com/poetapp/node/blob/2ab5f73dd60cccad2aa4139746b2c584c3559e97/src/Configuration.ts#L43-L49

https://github.com/poetapp/node/blob/2ab5f73dd60cccad2aa4139746b2c584c3559e97/src/BlockchainReader/BlockchainReader.ts#L51-L59

https://github.com/poetapp/node/blob/2ab5f73dd60cccad2aa4139746b2c584c3559e97/src/BlockchainWriter/BlockchainWriter.ts#L58-L66

One issue I'm worried about is that I'm not seeing a plain `auth` option in bitcoin-core:

https://github.com/ruimarinho/bitcoin-core/blob/e139b738d616862347065cb17d16724a9751c723/src/index.js#L47-L66

I couldn't find it in the README either. 

If it doesn't support it, it should be trivial to add it, though. 

## Documentation

We should also add walkthrough documentation on how to create this the `rpcauth`.

## Priority

@geoffturk I'm adding this to the `Mainnet-launch` and not the `Mainnet-beta` milestone since I think this is a security optimization and other issues are more critical, but please adjust as you think best.

## Reference
- https://github.com/ruimarinho/docker-bitcoin-core#using-rpcauth-for-remote-authentication
- https://github.com/bitcoin/bitcoin/blob/master/share/rpcauth/rpcauth.py
- https://github.com/ruimarinho/bitcoin-core

**Comment by WesleyCharlesBlake** [comment]
QA is using RPC auth to connect to bitcoind already.

Dont think this issue is applicable any more? I dont think there are code specific changes that need to take place

**Comment by WesleyCharlesBlake** [comment]
RPC auth still requires you to provide a username and password though, albeit hashed https://github.com/ruimarinho/docker-bitcoin-core/blob/master/README.md#using-rpcauth-for-remote-authentication

**Comment by jwicks31** [comment]
I'm not really sure that it's possible to set up Bitcoin-Core with RPC Auth in the Node.

From the [docker-bitcoin-core docs](https://github.com/ruimarinho/docker-bitcoin-core/blob/master/README.md#using-rpcauth-for-remote-authentication): 
`You can now connect via bitcoin-cli or any other compatible client. You will still have to define a username and password when connecting to the Bitcoin Core RPC server.`

And from the [Bitcoin-Core Docs](https://github.com/ruimarinho/bitcoin-core#arguments):
`[username]` _(number)_: The RPC server user name.
`[password]` _(string)_: The RPC server user password.

@WesleyCharlesBlake what steps were there to get the bitcoind instances running with RPC Auth?

**Comment by WesleyCharlesBlake** [comment]
@jwicks31 @warrenv @lautarodragan : this is how I got RPC auth working.

```bash
$ curl -sSL https://raw.githubusercontent.com/bitcoin/bitcoin/master/share/rpcauth/rpcauth.py | python3 - my-username
...
String to be appended to bitcoin.conf:
rpcauth=my-username:49cfbb8280d44d11a7603a94dcdfafef$cdf0fc4a54f7168978973711362cead587e59b7ca52f836d60fb4a2513a4c994
Your password:
vuAlC4KRGjLjBBZ5fQk7DIltZkTkrzSsOUAJyZRa2bI=

```

Then in the bitcoin config, remove the `rpcusername and rpcpass` values, and replace it with the `rpcauth=<username>:<salt_hash>` output by above.

Then in node, you provide the same bitcoin creds, however you provide the password that would be output. ie
```
Your password:
vuAlC4KRGjLjBBZ5fQk7DIltZkTkrzSsOUAJyZRa2bI=
```

**Comment by jwicks31** [comment]
@WesleyCharlesBlake Thanks! I tried that yesterday, but each time I tried running the containers I was getting this warning: `WARNING: The bb36069c7753e983b49407361d8c6a856263c52af5a4832f7b2ae3ae60f8227d variable is not set. Defaulting to a blank string.` This would be the hash after the `$` in the <username>:<salt>$<hash> string.

**Comment by warrenv** [comment]
@jwicks31 Where did you set the variable? Try wrapping it in single quotes or adding a '\' before the dollar sign.

**Comment by jwicks31** [comment]
@warrenv Inside of local-dev in place of the rpcuser + rpcpassword. I tried wrapping in single quotes, adding a " before the $ and both together, but no luck.

**Comment by geoffturk** [comment]
Reassigning to @warrenv for review/prioritization in PML1.

**Comment by WesleyCharlesBlake** [comment]
I think we can close this out. Im using RPC Auth in QA and prod now
