### ISSUE TITLE
dockerfile using npm install instead of npm ci

### ISSUE THREAD

**Issue by lautarodragan** [poetapp/node#452]
Shouldn't it be using `npm ci`?

`npm ci` is the only command guaranteed to make a clean install and follow package.json and package-lock.json to the letter, not introducing modifications to them.

`npm i` usually introduces modifications to `package-lock.json`.

I'd expect all containers generated out of an image to be as similar as possible (unless I'm intentionally introducing modifications).

@warrenv @WesleyCharlesBlake

**Comment by warrenv** [comment]
We should probably add this to all our docker builds. I'm not sure how we'll enforce it for local development for those who do not use containers during the development process. But this is s tep in the right direction now that we are using the latest version on node (and thus latest npm).

**Comment by lautarodragan** [comment]
I agree.
