### ISSUE TITLE
refactor CI config

### ISSUE THREAD

**Issue by WesleyCharlesBlake** [poetapp/node#517]
### Problem
Right now the, the travis.yml config breaks on make ipfs with write errors. This is a strange, runtime anomaly that occurs when Docker fails to write to the storage driver . We do not have control over this as the build environment is managed by Travis.

We also have  some things added into the travis environment, which may not be needed, since these are handled in the Docker image itself:
```
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install gcc-5 g++-5
  - sudo rm /usr/bin/g++
  - sudo ln -s /usr/bin/g++-5 /usr/bin/g++
```

### Solution
Refactor the entire travis config, and leverage docker-compose or a more a sane approach to running the backing services than with make recipes.

seeing as we only perform a lint and test coverage in the script, we can simplify the build config drastically.

```
script:
  - npm run lint
  - npm run coverage
```

And make it more future proof for when we have integration/unit tests in place. Rightnow from what I can, node only really runs the `dist/babel/test/PrepareDB.js` which prepares mongo and one function `async function insertTestWorks` that writes to the db. 

I think we should re-order the travis config, to better handle the starting up of services as containers, the test DB preparation, the lint and coverage, and resolve the weird as hell make errors we get sporadically. 

---
Moved from poetapp/random#177
/cc @WesleyCharlesBlake

**Comment by warrenv** [comment]
I agree that this needs some attention and it's required that a bunch of prep work be done first.
The coverage script runs unit tests and two types of integration tests.
The integration tests are going to be refactored now that we can properly inject config into the app instance. 
Functional tests will be added to travis builds once this is merged: https://github.com/poetapp/node/pull/509 and will probably require it's own docker-compose file.
