### ISSUE TITLE
docker-compose changes broke local development from node repo?

### ISSUE THREAD

**Issue by kennylavender** [poetapp/node#523]
unable to test for #522 , node is unable to connect to RMQ, seems to be an issue in master as well.

Here is what I am running from the node repo.

```
docker-compose up -d --build
docker-compose stop poet-node
npm run build
npm run start
```

All modules are getting this error.
```
[2] [2018-10-05T23:05:31.500Z] ERROR (5396 on Kenneths-MacBook-Pro.local): BlockchainReader was unable to start
[2]     exception: {
[2]       "stack": [
[2]         "Error: Unable to connect to RMQ at amqp://localhost. Handshake terminated by server: 403 (ACCESS-REFUSED) with message \"ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.\"",
[2]         "    at Messaging.start (/Users/kennethlavender/projects/poet/node/dist/babel/src/Messaging/Messaging.js:13:23)"
[2]       ],
[2]       "message": "Unable to connect to RMQ at amqp://localhost. Handshake terminated by server: 403 (ACCESS-REFUSED) with message \"ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.\"",
[2]       "type": "Error"
[2]     }
```

Looks like there was more docker-compose changes, is this the cause?

@warrenv I think you were tackling the changes to docker-compose?

**Comment by kennylavender** [comment]
yeah, looks like running the code via `npm run start` and `npm run watch` are no longer provided with the correct env variables maybe.

**Comment by geoffturk** [comment]
We should be running these inside of docker-compose so all the env vars are taken care automatically. Let's just standardize on local-dev for testing/development flow going forward.

**Comment by warrenv** [comment]
I'll echo what Geoff said above - we should be using containers for all development.

@kennylavender If you want to run outside the containers, it is the developer's responsibility to look in the docker-compose files and understand what env vars might need to be set before running any
commands directly in the shell.  In this particular case, it looks like the RABBITMQ_URL needs to be specified to include the username and password (see docker-compose.yml).

**Comment by kennylavender** [comment]
@warrenv @geoffturk This does not seem like a good idea as local-dev is private. Are we no longer supporting node as a public repo for outside devs to contribute and start on their own? We should at least have directions then on where to find the defaults. @lautarodragan

**Comment by geoffturk** [comment]
Ultimately local-dev will be made public, so outside contributions and experimentation will be facilitated.

**Comment by warrenv** [comment]
We are only supporting docker container based workflows for our repos. 

It becomes too much of a support burden if we have to help devs get setup on every possible combination of OS versioning among macos, windows and linux. Docker provides a single, unified environment via the same runtime image and configuration (using docker-compose) across all docker supported OSes.

**Comment by warrenv** [comment]
The following is needed to run outside of a container:
```bash
  $ RABBITMQ_URL=amqp://admin:adminPass@localhost npm start
```

**Comment by lautarodragan** [comment]
I'm re-opening this. I do agree with Warren in only supporting docker based workflows officially, but this issue is simple enough to fix: https://github.com/poetapp/node/pull/536
