### ISSUE TITLE
Deprecated signrawtransaction

### ISSUE THREAD

**Issue by lautarodragan** [poetapp/node#535]
`signrawtransaction` has been deprecated. 

We're currently passing `-deprecatedrpc=signrawtransaction` to bitcoind, but the rpc will probably be [removed in the next release of Bitcoin Core](https://github.com/bitcoin/bitcoin/pull/12490).

https://github.com/poetapp/node/blob/b71115ac4ffd877efa338885cba91c040ccb58bf/docker-compose.yml#L31-L43

We should be able to update our code base to use [`signrawtransactionwithwallet`](https://github.com/bitcoin/bitcoin/pull/10579) instead — the diff in the PR shows the tests being updated to use this new RPC with no changes to the arguments.

See https://github.com/bitcoin/bitcoin/issues/10570.

@geoffturk adding this to mainnet-launch since it's not breaking right now, but the breaking change was already merged to master so we'll want to start work on this one as soon as we finish mainnet-beta.

**Comment by lautarodragan** [comment]
Update: it'll be removed in v0.18.0

**Comment by geoffturk** [comment]
@warrenv ^^^^^^^ Don't update to 0.18 without first discussing it here. It will introduce a breaking change to bitcoind.

**Comment by warrenv** [comment]
Update: This new call is not part of the bitcoin-core npm package yet.

**Comment by WesleyCharlesBlake** [comment]
I will test this out in QA in the morning. I need to make changes to the bitcoind configs

**Comment by lautarodragan** [comment]
We can now use https://www.npmjs.com/bitcoins
