### ISSUE TITLE
Broken Semantic Release?

### ISSUE THREAD

**Issue by lautarodragan** [poetapp/node#637]
https://www.npmjs.com/package/@po.et/node lists last publish as 15 days ago.
There's more recent commits in master, and https://hub.docker.com/r/poetapp/node/tags/ tagged `latest` 14 hours ago.

[This Travis build](https://travis-ci.org/poetapp/node/builds/445410934?utm_source=github_status&utm_medium=notification) has the following output in the end:

```
$ npm run travis-deploy-once "npm run semantic-release"
The program 'npm' is currently not installed. To run 'npm' please ask your administrator to install the package 'npm'
```

**Comment by geoffturk** [comment]
@WesleyCharlesBlake Can you take a look at this one when you get a chance?

**Comment by WesleyCharlesBlake** [comment]
on it
