### ISSUE TITLE
Bug: BatchReader onPoetBlockAnchorsDownloaded

### ISSUE THREAD

**Issue by lautarodragan** [poetapp/node#651]
I forgot one update need in https://github.com/poetapp/node/pull/617

https://github.com/poetapp/node/blob/67c76843da35dd0e93fe6e2f9cce0002644b11e1/src/BatchReader/Router.ts#L45-L62

`poetBlockAnchors` can now be an empty array, in which case `this.claimController.addEntries` should not get called.

This is causing MongoDB to throw an error down the line.

The error doesn't affect anything (it gets caught in the upper layers and logged instead of being ignored), but better to fix it.

**Comment by krobi64** [comment]
Fixed by #697
