### ISSUE TITLE
Add Feature Toggles

### ISSUE THREAD

**Issue by kennylavender** [poetapp/node#685]
Feature toggles will enable us to create smaller PRs

**Comment by kennylavender** [comment]
An example and the reason I created this issue is that I noticed I could have used them for #612 

I could have layered smaller prs that worked but not quite complete without the endpoint being accessible. Then when we are happy with the endpoint we just enable it.

I had the code working in a simple way and now I am refactoring the PR to match the current code base, it's adding a ton more code that could have been a separate PR. I think it would have been easier for reviewers in smaller PRs.

This is something I imagine we tackle post mainnet.

**Comment by kennylavender** [comment]
There may be a better solution than feature toggles for an api like this, maybe env variables to turn on/off the endpoint might be a better way of going about it.

**Comment by lautarodragan** [comment]
Alright. Let's discuss after mainnet.
