### ISSUE TITLE
Linting

### ISSUE THREAD

**Issue by lautarodragan** [poetapp/node#70]
We want linting rules to be enforced by Travis.

The current linting rules for the node are completely out of date and were never enforced.

poetapp/frost-web has more recent rules. I'd love to get those tested in this repo and see how well they behave. They may need some changes, or the code may need to mark some exceptions.

If we can get both repos to share the same set of rules, we can later extract the rules into a separate GH repo and npm package and install it as a dependency in all our TypeScript projects.

**Comment by lautarodragan** [comment]
@warrenv @wzalazar I think we can close this now, right?

**Comment by wzalazar** [comment]
@lautarodragan it's done
