### ISSUE TITLE
Blockchain Confirmations: Transaction Retries (Naive)

### ISSUE THREAD

**Issue by lautarodragan** [poetapp/node#707]
## Goal

We need a way to track how _old_ a transaction is, and replace it by a new one if older than a configured amount.

## Reference

RDD: [Blockchain Confirmations](https://github.com/poetapp/documentation/blob/master/rdd/blockchain-confirmations.md#blockchain-confirmations)

Vague description and implementation tip in pseudo-js: [#BlockchainWriter](https://github.com/poetapp/documentation/blob/master/rdd/blockchain-confirmations.md#blockchainwriter)

Parent issue: https://github.com/poetapp/node/issues/46

## Implementation Details
* [x] `BlockchainWriter` will need to store the current date [along with the `transactionId`](https://github.com/poetapp/node/blob/9edaf9bf67a741bf34c0a9791b704fa3e3f5567a/src/BlockchainWriter/Controller.ts#L90).
* [x] `BlockchainWriter` will need to be aware of newly scanned blocks
  * [x] Update entries in the `blockchainWriter` collection where `txId in block.transactionIds` setting `blockHash` and `blockHeight`
  * [x] ~Upsert entries in the `blockchainWriter` collection, comparing their creation date against the block creation date. If the don't already have a `blockHeight` set and the date difference is greater than the configured amount, clear out `txId` and `transactionCreationDate` fields and increasing an `attempts` field.~ #781 Create a service to check for `blockchainWriter` collection entries that have a txId, don't have a blockHash and blockHeight and their `transactionCreationDate` is older than the transaction max age. Remove the txId from those entries and increment an `attempts` field.
*  ~The View module should update with confirmation information (`transactionCreationDate`), to be returned by the API `GET /works` in the `.timestamp` object.~
* [x] The Health module should update with retry information, grouping amount of attempts by amount of transactions. IOW, how many second attempts, how many third attempts, and so forth.

Clearing out the `txId` will have the next iteration of the service pick it up again, creating a new transaction and broadcasting it.

## New Configuration Options

- `purgeStaleTransactionsIntervalInSeconds`
- `maximumTransactionAgeInBlocks`

## Out of Scope

- Smarter mechanism for retries, like upping fee. 

## Related Work

Jesse is introducing a `feeEstimateMinTargetBlock` configuration option in [Estimated SmartFee from BitcoinCore](https://github.com/poetapp/node/pull/680/files). This configuration option is used by the Health endpoint to estimate the fee. Currently it's not used by the BlockchainWriter, but it could make sense to do so, in which case it could also make sense to use it to measure transaction age.

## Smaller PRs

This can lead to a pretty big PR if tackled all at once. There's some things that could be split, like the Health part.

**Comment by kennylavender** [comment]
Seems this issue description and RDD were out of sync a bit and described different solutions.

@krobi64 and I realized the RDD solution was the better way to go.

The date solution described here will prematurely wipe transactions IDs if the blockchain reader is playing catch up.

The RDD doc uses blockHeights instead of dates and a `createBlockHeight` get stored with the transaction entry when the transactions are created. We think if we use the bitcoind instances block count as the `createBlockHeight` it should prevent premature transaction ID wiping. The only concern here is that the bitcoind instance needs to be synced or it can still wipe transactions prematurely. Probably need to look into a way to avoid this in the future.

**Comment by lautarodragan** [comment]
@kennylavender 

> Seems this issue description and RDD were out of sync a bit and described different solutions.

Sorry about that. The version in the issue is more up to date, but I wasn't explicit about that or why it was different.

> The only concern here is that the bitcoind instance needs to be synced or it can still wipe transactions prematurely. 

This is the reason I switched to using dates instead of block heights.

> The date solution described here will prematurely wipe transactions IDs if the blockchain reader is playing catch up.

I don't understand this. Can you elaborate?

If we're comparing the date at which our transaction was broadcasted against the creation date of the block we just scanned, in what case would that lead to premature wipe?

**Comment by krobi64** [comment]
@geoffturk Please review what I wrote and see if it is sufficient. This has a few more PRs before fully implemented. So I tried to not provide too much 'coming soon' detail.

**Comment by geoffturk** [comment]
OK. Looks good to me.

**Comment by krobi64** [comment]
Per conversation with @lautarodragan we are not forwarding the `transactionCreationDate`, which is now the `creationBlockHeight` to the View module.
