### ISSUE TITLE
Replace koa-body with koa-bodyparser

### ISSUE THREAD

**Issue by warrenv** [poetapp/node#780]
snyk flags a high-severity bug with koa-body and it does not look like the maintainers can agree on a solution. We should try switching to koa-bodyparser (or possibly another).

**Comment by geoffturk** [comment]
@kennylavender Can you take a look at fixing this one with priority over the PML1 tasks? Thanks.

**Comment by kennylavender** [comment]
The snyk issue actually seems to be resolved by koa-body 4.0.0, but snyk has not yet been updated.

https://snyk.io/vuln/npm:koa-body:20180127

https://github.com/dlau/koa-body/issues/75

https://github.com/dlau/koa-body/pull/89

https://www.npmjs.com/package/koa-body#breaking-changes-in-v34

Not sure if we still want to look into replacing it? koa-bodyparse does not seem nearly as robust and doesn't provide multipart-form uploads it seems so we would need a new alternative, or handle the multipart file uploads with one of the upstream libraries like formidable or something.

**Comment by kennylavender** [comment]
^ @warrenv @geoffturk

**Comment by warrenv** [comment]
Thanks for digging deeper into that @kennylavender! It was not clear to me in reading the PRs that the problem was ever addressed. Going back thru and reading them again, I see that it was resolved. 
I'm not sure why snyk is still flagging this - I told it to ignore this problem.

**Comment by MarkHerhold** [comment]
Hey all, I'm a maintainer over at koa-body. The Snyk team has now marked the vulnerability as only affecting versions < 3.0.0.
